### ISSUE TITLE
A question on the security of wasi-libc data structures

### ISSUE THREAD

**Issue by jeffy1009** [WebAssembly/wasi-sdk#152]
I was looking at how file system access control (as part of capability-based security) is done in WASI using Lucet.
If I figured correctly, wasi-libc is compiled together with the wasm module, and I saw the file system access control logic is located in wasi-libc (`libc-bottom-half/sources/preopen.c`).
It seems that the data structures there end up located in the linear memory of the wasm module.
It seems possible then to corrupt the data structure there to bypass the file system access control logic.
I'd appreciate if someone would tell me if I've lost it at some point or there is some other mechanism to protect them.

**Comment by sbc100** [comment]
The actual enforcement of any access control is performed outside the wasm module by the embedder that implements the wasi syscalls.

What is it in https://github.com/WebAssembly/wasi-libc/blob/master/libc-bottom-half/sources/preopens.c that are you referring too?

**Comment by sunfishcode** [comment]
Security enforcement happens within the implementations of the WASI functions, outside of the application. A function like `path_open` takes a directory handle and a path, and will fail if the path doesn't stay within the given directory. (In Lucet, the code is in the `wasi-common` module). Applications can corrupt their own linear memory, but that won't give them access to directory handles that weren't granted to them.

The preopen.c's purpose is to provide compatibility with application code that expects to be able to open absolute paths. If the program does `open("/some/path"`, ...)`, what that does in wasi-libc is looks up "/some/path" in a table which has the directory handles which have been granted to the application, so that it can be transparently rewritten into a handle + relative path. But it's limited to handles it's been granted; it can't forge new ones.

This does mean the granularity of access is the whole wasm instance, rather than something narrower. If you grant a directory handle to a wasm instance, in general you have to assume that the whole instance has access to that handle, because as you observe, it might corrupt its own internal state. Memory-safe source languages can help with this, but from the perspective of a consumer of wasm, you generally can't assume you know what language a module was compiled from.

**Comment by jeffy1009** [comment]
Thanks for the explanations. Together with some more deeper look into the code, I think I have a better understanding about how it works now. I was looking at `preopens` list and thought if I corrupt the path prefix I could bypass the checks but those were just the virtual directory path given to a module, not a actual directory handle. 

I also thought if a wasm module can corrupt a vmctx pointer that seems to be given as the first argument of every function call in side wasm as well as the WASI API calls. I thought if it will be possible to impersonate another module by corrupting that pointer but it seems that Lucet checks for that case by checking against a instance pointer that's stored in a thread local `CURRENT_INSTANCE` variable.

**Comment by sunfishcode** [comment]
The `vmctx` pointer is also outside the control of wasm code; it's an implicit argument that doesn't appear in the wasm signature.

**Comment by sunfishcode** [comment]
This appears to be answered; feel free to re-open or file new issues if you have further questions!
