### ISSUE TITLE
Request release new version wasi-sdk,

### ISSUE THREAD

**Issue by lygstate** [WebAssembly/wasi-sdk#202]

**Comment by ricochet** [comment]
wasi-sdk 13 just dropped but it appears to be missing assets. @sunfishcode is this release in progress?

Missing assets that were in the previous release:
- libclang_rt.builtins-wasm32-wasi-12.0.tar.gz111 KB
- wasi-sdk-12.0-linux.tar.gz47.2 MB
- wasi-sdk-12.0-macos.tar.gz43 MB
- wasi-sdk-12.0-mingw.tar.gz135 MB
- wasi-sdk_12.0_amd64.deb30.8 MB
- wasi-sysroot-12.0.tar.gz1.65 MB

**Comment by sbc100** [comment]
IIRC these assets get uploaded manually after the fact, rather than automatically.  I think @pchickey has normally taken care of it.

**Comment by ricochet** [comment]
I downloaded the assets from the most recent CI and noticed that they still have version 12 in the path. There might be a version file that needs to be bumped.

**Comment by sunfishcode** [comment]
I'm uploading the assets from the latest build to the release now.

It does appear that they have the "12" version number. Offhand I'm not sure which script does that, but I'll look into it.

**Comment by sunfishcode** [comment]
The assets are now uploaded, though they have the "12" in the name.

The build script that generated the names was using `git describe` which was skipping the wasi-sdk-13 tag because it wasn't an annotated tag. I've now added an annotation, which should fix the script. There's a new CI run running now; when that completes, I'll upload the newly generated artifacts.

**Comment by sunfishcode** [comment]
Everything is now built with the corrected version numbers, and uploaded to the wasi-sdk-13 release!
