### ISSUE TITLE
wasm-ld: error: unknown argument: -search_paths_first

### ISSUE THREAD

**Issue by weiqingtangx** [WebAssembly/wasi-sdk#250]
```
205 warnings generated.
[100%] Linking CXX executable f2wasm
clang-14: warning: argument unused during compilation: '-arch x86_64' [-Wunused-command-line-argument]
wasm-ld: error: unknown argument: -search_paths_first
wasm-ld: error: unknown argument: -headerpad_max_install_names
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [f2wasm] Error 1
make[1]: *** [CMakeFiles/f2wasm.dir/all] Error 2
make: *** [all] Error 2
```
Hi Guys, I run it on an Apple M1 Chip computer(MacBook Pro (13-inch, M1, 2020)), how can I fix this problem? Thanks

**Comment by sbc100** [comment]
Your building system seems to be injecting link flags that are not compatible with the wasm linker.   `-search_paths_first` and `-headerpad_max_install_names` look like they are both specifc the Mach-O linker of macOS.  You need to figure out where in the build system they are being added (most like in a CMakeLists.txt file somewhere) and remove then (along with `-arch x86_64` which won't work when targeting wasi).

BTW, I would highly recommend switching to the ninja cmake generator (-G Ninja) so that when errors like this occur the offending command line is shown (this is just one of many advantages of using the ninja generator over the Makefile one).

**Comment by weiqingtangx** [comment]
@sbc100 Thanks for your reply. I'm pretty sure there are not added in my CMakeLists.txt.  And, after I switch to the ninja cmake generator, I found them in this place. I can't find a way to remove them.
![image](https://user-images.githubusercontent.com/5905640/185304662-60814459-8535-4527-ae4e-69a29bb796b3.png)

**Comment by sbc100** [comment]
You need to tell cmake the you are cross compiling to wasi and not building a macOS project.  

The easiest way to do that is to use the cmake crosstool that is part of wasi-sdk: https://github.com/WebAssembly/wasi-sdk/blob/main/wasi-sdk.cmake.
