### ISSUE TITLE
Docker build failuire

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/wasi-sdk#289]
The Docker build is currently failing:

https://github.com/WebAssembly/wasi-sdk/actions/runs/3914579553/jobs/6691806356

```
#26 pushing layers 1.4s done
#26 ERROR: failed to push ghcr.io/webassembly/wasi-sdk:main: failed to copy: io: read/write on closed pipe
------
 > exporting to image:
------
ERROR: failed to solve: failed to push ghcr.io/webassembly/wasi-sdk:main: failed to copy: io: read/write on closed pipe
Error: buildx failed with: ERROR: failed to solve: failed to push ghcr.io/webassembly/wasi-sdk:main: failed to copy: io: read/write on closed pipe
```

@anuraaga

**Comment by stellarpower** [comment]
I'm unable to pull the image (as an end user) either:
```
$ podman pull  ghcr.io/webassembly/wasi-sdk
Trying to pull ghcr.io/webassembly/wasi-sdk:latest...
Error: initializing source docker://ghcr.io/webassembly/wasi-sdk:latest: unable to retrieve auth token: invalid username/password: unauthorized
```

**Comment by anuraaga** [comment]
Yesterday there were several failed builds with network-related errors like at various jobs and steps

https://github.com/WebAssembly/wasi-sdk/actions/runs/3907720165/jobs/6677220928
https://github.com/WebAssembly/wasi-sdk/actions/runs/3907722523/jobs/6677224962

Other builds since that one have succeeded so hopefully things have stabilized but there isn't really any change to make I think.

For the pull issue, we're still waiting on an admin to fix the permissions I think /cc @sbc100

**Comment by sbc100** [comment]
I'm not an admin IIUC.  I think that would be @sunfishcode or @dschuff

**Comment by sunfishcode** [comment]
What needs to be changed?

**Comment by anuraaga** [comment]
@sunfishcode Currently the package is private and seems that repository maintainers can't change it to public - there is an org level setting to allow repositories to publish public packages which I think needs to be flipped

**Comment by abrown** [comment]
Closing as this seems to no longer be an issue &mash; Docker builds are succeeding.
