### ISSUE TITLE
Using wasi-sdk-20 pre-release on Ubuntu 20.04

### ISSUE THREAD

**Issue by eloparco** [WebAssembly/wasi-sdk#303]
Hello,
In a GitHub action job on Ubuntu 20.04, I'm trying to use the wasi-sdk-20 pre-release, but I'm getting the following eror:
```bash
/opt/wasi-sdk/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/wasi-sdk/bin/clang)
/opt/wasi-sdk/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/wasi-sdk/bin/clang)
/opt/wasi-sdk/bin/clang: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/wasi-sdk/bin/clang)
```
Is there any planned fix to support older versions of glibc?
Thanks

**Comment by abrown** [comment]
@yamt had mentioned this in a comment previously, but I personally was not too interested in maintaining compatibility with a bunch of old glibc versions ("how far to go back?" "would this cause friction with future integration?" etc.). IIUC, this boils down to using Ubuntu's 20.04 image during compilation instead of 22.04; I don't understand what restrictions are preventing other projects from also using 22.04? Is this request of wasi-sdk just a symptom of another issue somewhere else? That being said, I'm actually not opposed to supporting some older versions of glibc, though; I would gladly review PRs along these lines if we figure out a limit to the versions supported and it meshes with the work I did to script the release process in https://github.com/WebAssembly/wasi-sdk/pull/295.

**Comment by yamt** [comment]
> @yamt had mentioned this in a comment previously, but I personally was not too interested in maintaining compatibility with a bunch of old glibc versions ("how far to go back?" "would this cause friction with future integration?" etc.). IIUC, this boils down to using Ubuntu's 20.04 image during compilation instead of 22.04; I don't understand what restrictions are preventing other projects from also using 22.04? Is this request of wasi-sdk just a symptom of another issue somewhere else? That being said, I'm actually not opposed to supporting some older versions of glibc, though; I would gladly review PRs along these lines if we figure out a limit to the versions supported and it meshes with the work I did to script the release process in #295.

as far as i know, no one is asking "compatibility with a bunch of old glibc versions".
just a compatibility with commonly used distributions like ubuntu 20.04.
it's normal for people not want to upgrade the OS. (after all, it's the whole point of LTS versions i guess.)

**Comment by abrown** [comment]
Ok, now that #307 is merged should we close this? I will use the older versions in the `wasi-sdk-20` release but if anyone wants it earlier then I could replace the artifacts in the `wasi-sdk-20+threads` pre-release with the older version.

**Comment by yamt** [comment]
> Ok, now that #307 is merged should we close this? I will use the older versions in the `wasi-sdk-20` release but if anyone wants it earlier then I could replace the artifacts in the `wasi-sdk-20+threads` pre-release with the older version.

i want it "soon".

i have no idea when `wasi-sdk-20` will be.

**Comment by abrown** [comment]
@eloparco, can you try out the [`wasi-sdk-20`](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-20) release? It's binaries should be created from a tree that includes #307.

**Comment by eloparco** [comment]
Thanks! I tried it and it seems to work: https://github.com/bytecodealliance/wasm-micro-runtime/pull/2095
