### ISSUE TITLE
The wasi-sdk-20.0 for mingw contains an extra .m suffix

### ISSUE THREAD

**Issue by cphoskins** [WebAssembly/wasi-sdk#323]
wasi-sdk-20.0.m-mingw.tar.gz's contained directory is named `wasi-sdk-20.0.m` rather than `wasi-sdk-20.0`. Is the additional .m intentional? If so, that means the wasi-sdk retrieval and use between Linux and mingw now differ which would require conditional logic in our make files between platforms.

**Comment by abrown** [comment]
I think what is going on here is that the `version.sh` script is appending an `m` to the version because the Git directory is changed:

https://github.com/WebAssembly/wasi-sdk/blob/c891cd2036d5630e67826f70aec9c0ba117c67e9/version.sh#L4

I don't know why this is, though. When I've hurriedly noticed this before I thought that it had something to do with the Windows action runners for CI &mdash; some difference between the Windows environment and the rest? I We could just rename this artifact, which I'm happy to do, but this would continue to happen in future releases. Are you interested in looking into this?

**Comment by cphoskins** [comment]
@abrown , I can take a look at it, but I wouldn't be able to start until 2023-04-21. If that works, then I would be happy to dig in.

**Comment by abrown** [comment]
Yeah, that would be great! (cc: @yamt or @eloparco who had a similar comment about this recently, IIRC).
