### ISSUE TITLE
Consider adding main() signature with environment argument

### ISSUE THREAD

**Issue by rene-fonseca** [WebAssembly/wasi-sdk#91]
Per C Standard, J.5.1 [ISO/IEC 9899:2011] main with environment is ok and is supported by all the main platforms.

Test could be something like this:
```
#include <stdio.h>

int main(int argc, /*const*/ char* argv[], /*const*/ char* envp[])
{
  if (argc < 1) {
    return 1;
  }

  for (int i = 0; i < argc; ++i) {
    const char* arg = argv[i];
    if (!arg) {
      return 1; // do not allow nullptr argument
    }
    for (; *arg; ++arg) { // ensure memory is valid
    }
  }

  for (size_t j = 0; envp[j]; ++j) {
    const char* env = envp[j];
    if (!env) {
      return 1; // do not allow nullptr item
    }
    for (; *env; ++env) { // ensure memory is valid
    }
  }

  puts("hello from argc argv envp main!");
  return 0;
}
```

**Comment by sunfishcode** [comment]
The complicating factor here is that the underlying wasm platform doesn't work the way all other main platforms work. Wasm requires caller and callee signatures to match, so we can't use the trick that all other main platforms use, of passing extra arguments which the `main` function can simply ignore.

It takes a fair amount of [magic](https://github.com/CraneStation/wasi-libc/blob/master/libc-bottom-half/sources/__original_main.c#L9) to even support both the required forms of `main(void)` and `main(int argc, char *argv)`. It turns out the magic we have right now has some limitations, so we're [working on better magic](https://github.com/WebAssembly/tool-conventions/pull/134). Once that's done, we could consider what it would take to further add `envp` support.

Section J.5 of ISO C is about "Common Extensions" that "are not portable to all implementations", so this isn't required for conformance. It's just a question of whether there's a way we can support this extension without taking on more complexity than it's worth.

**Comment by rene-fonseca** [comment]
Ok, thanks.

**Comment by sunfishcode** [comment]
The "better magic" mentioned above has now landed. If anyone is interested in pursuing support for the `environ` parameter to main, please open an issue in the [`tool-conventions`](https://github.com/WebAssembly/tool-conventions/) repo, similar to https://github.com/WebAssembly/tool-conventions/pull/134, so we can coordinate between the various tools and libraries that would be affected -- at least clang, Emscripten, and wasi-libc, and possibly others.

As an additional piece of background information, [POSIX observes](https://pubs.opengroup.org/onlinepubs/9699919799/functions/exec.html) that the `envp` argument is not even needed for compatibility with historical Unix platforms:

> Since this volume of POSIX.1-2017 defines the global variable environ, which is also provided by historical implementations and can be used anywhere that envp could be used, there is no functional need for the envp argument.
